# Generated by Django 5.1 on 2024-08-28 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('payment_status', models.BooleanField()),
                ('cupon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cupon_app.cupon')),
            ],
        ),
    ]
