# Generated by Django 5.1 on 2024-08-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_app', '0002_clas_delete_class'),
        ('factor_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factor',
            options={'verbose_name': 'Factor', 'verbose_name_plural': 'FACTORS'},
        ),
        migrations.AddField(
            model_name='factor',
            name='class1',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='class_app.clas'),
        ),
    ]
