# Generated by Django 5.1 on 2024-08-28 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('class_app', '0002_clas_delete_class'),
        ('cupon_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('wallet', models.IntegerField(default=0)),
                ('clas', models.ManyToManyField(related_name='techer', to='class_app.clas', verbose_name='class')),
                ('cupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cupon_app.cupon')),
            ],
        ),
    ]
