# Generated by Django 5.1 on 2024-08-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title of the coupon.', max_length=50, verbose_name='Coupon Title')),
                ('expire_date', models.DateField(help_text='Enter the expiration date of the coupon.', verbose_name='Expiration Date')),
                ('percent', models.FloatField(help_text='Enter the discount percentage provided by the coupon.', verbose_name='Discount Percentage')),
                ('cupon_availability', models.BooleanField(help_text='Indicate if the coupon is currently available for use.', verbose_name='Cupon Availability')),
            ],
            options={
                'verbose_name': 'Cupon',
                'verbose_name_plural': 'Cupons',
            },
        ),
    ]
